### ISSUE TITLE
KeyboardAvoidingView not working with modal.

### ISSUE THREAD

**Issue by Jalson1982** [react-native-modal/react-native-modal#242]
I have a question about it. I have modal and in modal i have header, text and then text input and on bottom complete button. When open keyboard text input will not move . I tried set behaviour padding to KeyboardAvoidingView not work. If I set position in KeyboardAvoidingView it moves my button over text input and it still do not work. Any idea how to get this to work?
Here is gist:

https://gist.github.com/Jalson1982/9706a387d6e3abb929fc5206a367f9ea

**Comment by Jalson1982** [comment]
It is not easy to reproduce as there is bunch of logic needed to run it ... I tried to explain a little bit... 
Modal
<Text>
<Text>
<Text>
<TextInput>
<Button>
</Modal>

When press on text input it does not move it only in case when i use behaviour position but it looks so ugly. There is something strange and missing as I am using on login screen this too and it works normal.

**Comment by Hatko** [comment]
Have a similar issue

**Comment by mi-mazouz** [comment]
Why you closed this issue?

**Comment by afilp** [comment]
Same with react-native 0.61

**Comment by wwwtony5488** [comment]
Same issue within 0.62

**Comment by richardfelkl** [comment]
Same issue, on Android it's working and the KeyboardAvoidingView is shrinking and Modal is centered but ion iOS KeyboardAvoidingView is not shrinking when Modal is visible.
