### ISSUE TITLE
11.5.1 or newer TypeScript issue with styled components

### ISSUE THREAD

**Issue by inferusvv** [react-native-modal/react-native-modal#381]
## Versions

- react-native-modal: 11.5.1 or newer
- react-native:  0.61.5
- react: 16.12.0
- styled-components: 4.4.1

## Description

I see in change log was add TypeScript support. I use styled components and started get next error here:

```
const StyledModal = styled(Modal)`
  margin: 0;
`;
```

<img width="1258" alt="Снимок экрана 2019-12-01 в 21 40 51" src="https://user-images.githubusercontent.com/3227120/69918462-4fc80000-1483-11ea-86be-7eb1d6120060.png">

**Comment by mmazzarolo** [comment]
I'm not familiar with styled-components in react-native. Could it be because we need to expose the "style" prop in the TS interface?

**Comment by Sakarisson** [comment]
Not sure exactly what is the reason, but it has to do with the typings of `getDerivedStateFromProps`

**Comment by aldebout** [comment]
@rewieer I'm wondering why you're closing this.
I understand the need for maintenance and I'd like to thank you for doing that work, but this issue is still in need of resolution ;)

**Comment by ammichael** [comment]
Why is this closed? This issue is still happening

**Comment by duspada** [comment]
I'm also getting this error...

**Comment by luisgurmendezMLabs** [comment]
I know this is not the best but it at least avoids the typing error (the styles are applying to the Modal):
```
const Modal = styled((ModalBase as any))
```
This error should be fix tho as it might introduce some bugs

**Comment by rewieer** [comment]
@aldebout having no feedbacks since December I archived it. Since it pops up, i'm going to reopen it.
I'm not using styled components, unfortunately.

**Comment by jianxiao-chen** [comment]
I'm also getting this error...


> Workaround for now (the styles are applying to the Modal):
> 
> ```
> const Modal = styled((ModalBase as any))
> ```
> 
> This error should be fix tho as it might introduce some bugs

This works.

**Comment by lHersey** [comment]
Another workaround to keep typings:

```
import React, { FC } from 'react';
import { ModalProps } from 'react-native';
import ReactNativeModal from 'react-native-modal';

...

const ReactModal = styled((ReactNativeModal as unknown) as FC<ModalProps>)`
    display: flex;
    justify-content: center;
`;
```

**Comment by agnislav** [comment]
The error still exists. Use the `as any` workaround

**Comment by Will-PlatformBuilders** [comment]
Persists on

    react-native-modal: 11.10.0
    react-native: 0.64.1
    react: 17.0.2
    styled-components: 5.3.0
    @types/styled-components-react-native: 5.1.1

**Comment by ilanrot90** [comment]
still on

**Comment by SaidKherif** [comment]
Still on
"react-native-modal": "13.0.0",
"@emotion/native": "11.0.0",

**Comment by gabriel11447** [comment]
still on

"react-native-modal": "^13.0.0",
"react-native": "0.64.2",

**Comment by searesdavi** [comment]
Still on

**Comment by velcis** [comment]
Still on

**Comment by lindan4** [comment]
This seems to be an issue with newer versions of TypeScript and/or styled-components.

**Comment by xlecunff-pass** [comment]
Still having this issue with the latest version
