### ISSUE TITLE
Text input submit button not working on first click

### ISSUE THREAD

**Issue by akhilsanker** [react-native-modal/react-native-modal#416]
## Environment

react: 16.8.3 => 16.8.3 
      react-native: 0.59.8 => 0.59.8 
## Platforms

Both in Android and iOS
## Versions

- Android: 9
- iOS: 13.3
- react-native-modal: 11.4.0
- react-native: 0.59.8
- react: 16.8.3

## Description

Have a text input and submit and close button in the modal. The keyboard is autofocus and with the keyboard is opened and try to close or submit the inputs, the buttons are not working on the first click.
On first click the keyboard is closed and need to click on the button second time to submit.
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-03-24 at 13 01 59](https://user-images.githubusercontent.com/32122016/77399542-ac9f4b80-6dcf-11ea-98ad-4c65459290d5.png)

## Reproducible Demo

Step to reproduce:
1. A text input, close and submit button in modal.
2. The keyboard is auto-focused when the modal appears.
3. Try to close the modal, by clicking the close button with the keyboard opened.
4. On the first click the keyboard closed and need to tap again the close button to close the modal.

**Comment by ajgodp13** [comment]
I am having this same issue, are there any work arounds?

**Comment by mo-patel** [comment]
Is your content wrapped in a `<ScrollView />`? If so, try `keyboardShouldPersistTaps={'handled'}` in `<ScrollView>` props.

**Comment by rewieer** [comment]
Can you provide a github repository featuring this problem ?

**Comment by akhilsanker** [comment]
Hi @mo-patel,
Tried.But not working

**Comment by mo-patel** [comment]
@akhilsanker can you share the code for your modal so I can take a look at your layout?

**Comment by akhilsanker** [comment]
Hi @mo-patel 

    <ScrollView 
	refreshControl={
		<RefreshControl  tintColor={language.primary} refreshing={this.state.pullrefresh} onRefresh={() => this.onRefresh()} />
	}
	showsVerticalScrollIndicator={false}
	contentContainerStyle={style.scrollWrapper}>
		<KeyboardAwareScrollView 
			contentContainerStyle={{flexGrow: 1}} 
			alwaysBounceVertical="false"
			showsVerticalScrollIndicator={false}
			keyboardShouldPersistTaps="handled">
			<Card style={{elevation: 2, marginTop: 2}} >
				<CardItem>
					<Body>
 						...
					</Body>
				</CardItem>
			</Card>
			{/* -------------- modal to edit your response  ---------------------- */}
			<Modal isVisible={this.state.editRespModal}
				animationInTiming={1000}
				animationOutTiming={1000}
				backdropTransitionInTiming={800}
				backdropTransitionOutTiming={800}
				style={{zIndex: 99}}
				avoidKeyboard={true}
				autoFocus={true}									
			>
				<SafeAreaView style={{flex: 1}} >
				<KeyboardAwareScrollView contentContainerStyle={{  backgroundColor: '#fff' }}  keyboardShouldPersistTaps="handled" behavior={'position'}>
		           		<View style={{flex: 1}}>
		           			<View style={{backgroundColor: language.headerColor, justifyContent: 'center', height: 50, alignItems: 'center' }}>
		           				<Title style={{color: '#fff'}}>{language.editModalTitle}</Title>
		           			</View>
							<View style={{ flex: 1, marginTop: 20, padding: 10,}}>
									<View style={{flex: 1, justifyContent: 'center'  }}>
										<Text style={{fontSize: 16,fontWeight: '500', marginTop: 10}}>{language.yourResponseLabel}</Text>
										<TextInput style={style.textInputStyle}
											multiline={true}
											autoFocus={true}
											maxLength={255}
											textAlignVertical={'top'}
											underlineColorAndroid="transparent"
											selectionColor={language.headerColor}
											value={this.state.responseInput}
											onChangeText={(text) => this.responseAdded(text)}/>
									</View>
									<View style={{flex: 1, flexDirection: 'row', alignItems: 'flex-start' }}  >
										<Button
											title={language.closeLabel}
											buttonStyle={{backgroundColor: language.danger}}
											titleStyle={{fontWeight: '400'}}
											onPress={() => this.closeEditModal()}
											containerStyle={{marginHorizontal: 5, flex: 1}}
										/>
										<Button
											title={language.submitResponseBtn}
											disabled={this.state.buttonDisabled}
											buttonStyle={{backgroundColor: language.headerColor}}
											titleStyle={{fontWeight: '400'}}
											onPress={() => this.responseSubmit(this.state.detailsData.id)}
											loading={this.state.buttonLoading}
											containerStyle={{marginHorizontal: 5, flex: 2}}
										/>
									</View>
							</View>
						</View>
					</KeyboardAwareScrollView>
				</SafeAreaView>
			</Modal>
		</KeyboardAwareScrollView>
</ScrollView>

**Comment by mo-patel** [comment]
@akhilsanker can you try change your `keyboardShouldPersistTaps={'handled'}` to `keyboardShouldPersistTaps={'always'}` and let me know if this works?

**Comment by akhilsanker** [comment]
Hi @mo-patel,
I have tried that too. But didn't succeed.

**Comment by appify-waheed** [comment]
@mo-patel Same here I have tried with `keyboardShouldPersistTaps={'handled'}` and  `keyboardShouldPersistTaps={'always'} ` both not works.

**Comment by Psiiirus** [comment]
Run into the same problem and couldn't find a workaround...
For other parts of my app I use this lib https://github.com/APSL/react-native-keyboard-aware-scroll-view to have a properly working "KeyboardAvoid-View"
maybe this could be a good replacement for internally used KeyboardAvoidingView

**Comment by nafisholeh** [comment]
`keyboardShouldPersistTaps={'handled'}` works for me, but in my case, I need to put these props into both the `ScrollView` and [`KeyboardAwareScrollView`](https://github.com/APSL/react-native-keyboard-aware-scroll-view). 

My code more or less looks like this:
```
<ScrollView 
     keyboardShouldPersistTaps={'handled'}
>
   ...
      <KeyboardAwareScrollView
           keyboardShouldPersistTaps={'handled'}
      >
         ...
         <Modal>...</Modal>
         ...
      <KeyboardAwareScrollView>
   ...
<ScrollView>
```

**Comment by NishidaRyu416** [comment]
I am also encountering the same issue.
None of those options that could potentially fix the problem have worked.

**Comment by Walker0125** [comment]
any solution？

**Comment by enesbildiren95** [comment]
I use TextInput and TouchableOpacity in KeyboardAvaidingView component. I can not click TouchableOpacity when Keyboard is opened. When I press the TouchableOpacity, just Keyboard disappear. I want TouchableOpacity to work while Keyboard is active. Does anyone have an idea?

**Comment by xlcrr** [comment]
I am also looking for a solution

**Comment by enesbildiren95** [comment]
If you find anything, can you let me know? I'm still searching.

**Comment by xlcrr** [comment]
I made a question here too https://stackoverflow.com/questions/63103717/prevent-keyboard-dismiss-react-native-inside-modal

**Comment by xlcrr** [comment]
I got it working with native Modal component

Towards the root of my app, I have a `<Swiper />` element which is basically a ScrollView. Adding keyboardShouldPersistTaps="always" keyboardDismissMode="on-drag" to the Swiper as props solved my issue

**Comment by zmefz** [comment]
I had this issue and where trying to add Scroll View with `keyboardShouldPersistTaps="always"` with no result. Later I've found that there was a ScrollView at the page where the modal located which wrapped a whole page. So all what I did: I added `keyboardShouldPersistTaps="handled"` to this ScrollView and it helped me.

So the main idea is to walk up through the component tree and find for ScrollView and add `keyboardShouldPersistTaps="handled"` to it if exists. Otherwise just add it at place where you need it.

**Comment by Mehreen57** [comment]
@mo-patel thankyou very much for " keyboardShouldPersistTaps={'handled'}" this piece. It worked for me. thankss

**Comment by NishidaRyu416** [comment]
How about Flatlist?🤔

**Comment by izzyreal** [comment]
`keyboardShouldPersistTaps={'handled'}` works like a charm for my use case, many thanks.

**Comment by Coala1010** [comment]
Hello
I have the same problem

the button click is not working

```
<View style={{ flex: 1 }}>
      <Button title="Show modal" onPress={() => setShow(true)} />

      <Modal isVisible={show}>
        <View style={{ backgroundColor: 'white', alignItems: 'center' }}>
          <Text>Hello!</Text>
          <TextInput
            style={{ width: '100%', height: 300, borderColor: 'black', borderWidth: 1 }}
            />
          <Button title="Hide modal" onPress={() => setShow(false)} />
        </View>
      </Modal>
    </View>
```

**Comment by enesbildiren95** [comment]
Hey @Coala1010,

You should use <ScrollView keyboardShouldPersistTaps='handled'> component instead of View component in Modal.

**Comment by SRJDEV** [comment]
> Hi @mo-patel
> 
> ```
> <ScrollView 
> refreshControl={
> 	<RefreshControl  tintColor={language.primary} refreshing={this.state.pullrefresh} onRefresh={() => this.onRefresh()} />
> }
> showsVerticalScrollIndicator={false}
> contentContainerStyle={style.scrollWrapper}>
> 	<KeyboardAwareScrollView 
> 		contentContainerStyle={{flexGrow: 1}} 
> 		alwaysBounceVertical="false"
> 		showsVerticalScrollIndicator={false}
> 		keyboardShouldPersistTaps="handled">
> 		<Card style={{elevation: 2, marginTop: 2}} >
> 			<CardItem>
> 				<Body>
> 					...
> 				</Body>
> 			</CardItem>
> 		</Card>
> 		{/* -------------- modal to edit your response  ---------------------- */}
> 		<Modal isVisible={this.state.editRespModal}
> 			animationInTiming={1000}
> 			animationOutTiming={1000}
> 			backdropTransitionInTiming={800}
> 			backdropTransitionOutTiming={800}
> 			style={{zIndex: 99}}
> 			avoidKeyboard={true}
> 			autoFocus={true}									
> 		>
> 			<SafeAreaView style={{flex: 1}} >
> 			<KeyboardAwareScrollView contentContainerStyle={{  backgroundColor: '#fff' }}  keyboardShouldPersistTaps="handled" behavior={'position'}>
> 	           		<View style={{flex: 1}}>
> 	           			<View style={{backgroundColor: language.headerColor, justifyContent: 'center', height: 50, alignItems: 'center' }}>
> 	           				<Title style={{color: '#fff'}}>{language.editModalTitle}</Title>
> 	           			</View>
> 						<View style={{ flex: 1, marginTop: 20, padding: 10,}}>
> 								<View style={{flex: 1, justifyContent: 'center'  }}>
> 									<Text style={{fontSize: 16,fontWeight: '500', marginTop: 10}}>{language.yourResponseLabel}</Text>
> 									<TextInput style={style.textInputStyle}
> 										multiline={true}
> 										autoFocus={true}
> 										maxLength={255}
> 										textAlignVertical={'top'}
> 										underlineColorAndroid="transparent"
> 										selectionColor={language.headerColor}
> 										value={this.state.responseInput}
> 										onChangeText={(text) => this.responseAdded(text)}/>
> 								</View>
> 								<View style={{flex: 1, flexDirection: 'row', alignItems: 'flex-start' }}  >
> 									<Button
> 										title={language.closeLabel}
> 										buttonStyle={{backgroundColor: language.danger}}
> 										titleStyle={{fontWeight: '400'}}
> 										onPress={() => this.closeEditModal()}
> 										containerStyle={{marginHorizontal: 5, flex: 1}}
> 									/>
> 									<Button
> 										title={language.submitResponseBtn}
> 										disabled={this.state.buttonDisabled}
> 										buttonStyle={{backgroundColor: language.headerColor}}
> 										titleStyle={{fontWeight: '400'}}
> 										onPress={() => this.responseSubmit(this.state.detailsData.id)}
> 										loading={this.state.buttonLoading}
> 										containerStyle={{marginHorizontal: 5, flex: 2}}
> 									/>
> 								</View>
> 						</View>
> 					</View>
> 				</KeyboardAwareScrollView>
> 			</SafeAreaView>
> 		</Modal>
> 	</KeyboardAwareScrollView>
> ```


> Hi @mo-patel,
> I have tried that too. But didn't succeed

> Hi @mo-patel,
> I have tried that too. But didn't succeed.

Try to add the props   keyboardShouldPersistTaps={'handled'} in your modal, I was facing same issue inside Dialog, solved by adding   keyboardShouldPersistTaps={'handled'}  in Dilaog props like below:

  <Dialog
        visible={forgetPasswordDialog}
        dialogStyle={{ backgroundColor: 'transparent', elevation: 0}}
        **keyboardShouldPersistTaps={'handled'}**>

**Comment by SRJDEV** [comment]
<Dialog
        visible={forgetPasswordDialog}
        dialogStyle={{ backgroundColor: 'transparent', elevation: 0}}
        keyboardShouldPersistTaps={'handled'}>

**Comment by SRJDEV** [comment]
> Hi @mo-patel,
> I have tried that too. But didn't succeed.

Try to add the props keyboardShouldPersistTaps={'handled'} in your modal, I was facing same issue inside Dialog, solved by adding keyboardShouldPersistTaps={'handled'} in Dilaog props .
code -
`<Dialog
        visible={forgetPasswordDialog}
        dialogStyle={{ backgroundColor: 'transparent', elevation: 0}}
        **keyboardShouldPersistTaps={'handled'}**>`

**Comment by sarour** [comment]
> @mo-patel thankyou very much for " keyboardShouldPersistTaps={'handled'}. It worked for me. thanks

well done it is working fine.

**Comment by Valovoy** [comment]
> I had this issue and where trying to add Scroll View with `keyboardShouldPersistTaps="always"` with no result. Later I've found that there was a ScrollView at the page where the modal located which wrapped a whole page. So all what I did: I added `keyboardShouldPersistTaps="handled"` to this ScrollView and it helped me.
> 
> So the main idea is to walk up through the component tree and find for ScrollView and add `keyboardShouldPersistTaps="handled"` to it if exists. Otherwise just add it at place where you need it.

You are the best! It's really work

**Comment by Yeasirarafat53** [comment]
> Is your content wrapped in a `<ScrollView />`? If so, try `keyboardShouldPersistTaps={'handled'}` in `<ScrollView>` props.

Thanks man. its works for me

**Comment by saiutkarsh33** [comment]
<Modal
  visible={chatModalVisible}
  animationType="slide"
  onRequestClose={() => setChatModalVisible(false)}
>
  <SafeAreaView style={styles.modalContainer}>
    <Text
      style={{
        fontSize: 30,
        fontWeight: 'bold',
        alignSelf: 'flex-start',
        marginBottom: 20,
      }}
    >
      Event Chat
    </Text>
    <KeyboardAvoidingView

      behavior={Platform.OS === "ios" ? "padding" : "height"}
      style={styles.container}
    >
    <ScrollView keyboardShouldPersistTaps="handled">
      {messages.map((message, index) => (
        <Text key={index}>
         {message.name}: {message.content}
        </Text>
      ))}
    </ScrollView>
    <TextInput
      style={{height: 40, borderColor: 'gray', borderWidth: 1, borderRadius: 10}}
      onChangeText={setNewMessage}
      value={newMessage}
      multiline={true}
  numberOfLines={4} 
  onSubmitEditing={handleSendMessage}
    />
        <Button onPress={handleSendMessage} style={styles.sendButton}>
          Send
        </Button>

        <Button onPress={() => setChatModalVisible(false)} style={styles.closeButton}>
          Close
        </Button>
      
    </KeyboardAvoidingView>
  </SafeAreaView>
</Modal>


hey the keyboardShouldPersistTaps="handled" isnt workng for me :(

**Comment by Adil7767** [comment]
```
import { Formik } from 'formik'
import React from 'react'
import {
  ActivityIndicator,
  Image,
  `KeyboardAvoidingView,`
  SafeAreaView,
  ScrollView,
  StyleSheet,
  Text,
  TextInput,
  TouchableOpacity,
  View,
} from 'react-native'
import Modal from 'react-native-modal'
import * as yup from 'yup'
import close from '../../Assets/Images/close.png'
import { colors } from '../../Config/colors'

const RejectionModal = ({
  isVisible,
  onBackdropPress,
  onSubmit,
  isloading,
}) => {
  const validationSchema = yup.object({
    rejection_reason: yup.string().trim().required().label('Reason'),
  })

  return (
    <SafeAreaView>
      <KeyboardAvoidingView>
        <Modal
          style={styles.madalStyle}
          isVisible={isVisible}
          onBackButtonPress={onBackdropPress}
          onBackdropPress={onBackdropPress}
          animationIn="slideInUp"
          animationOut="slideOutDown"
          animationInTiming={500}
          animationOutTiming={500}
        >
          <ScrollView
            keyboardShouldPersistTaps={'handled'}
            style={styles.mainContainer}
          >
            <View style={styles.header}>
              <Text style={styles.headerText}>Reason</Text>
              <TouchableOpacity onPress={onBackdropPress}>
                <Image source={close} style={styles.closeImg} />
              </TouchableOpacity>
            </View>
            <Formik
              enableReinitialize
              validationSchema={validationSchema}
              initialValues={{
                rejection_reason: '',
              }}
              onSubmit={(values) => onSubmit(values)}
            >
              {({ errors, handleChange, handleSubmit, values, handleBlur }) => (
                <>
                  <View style={{ paddingHorizontal: 16, paddingVertical: 8 }}>
                    <Text style={styles.lableStyle}>Reason</Text>
                    <TextInput
                      numberOfLines={6}
                      multiline={true}
                      style={styles.textInput}
                      placeholder="Type reason"
                      placeholderTextColor={'rgba(82, 83, 83, 0.5)'}
                      onChangeText={handleChange('rejection_reason')}
                      onBlur={handleBlur('rejection_reason')}
                      value={values?.rejection_reason}
                    />
                    <Text style={styles.errorText}>
                      {errors.rejection_reason}
                    </Text>
                    <View style={styles.btnView}>
                      <TouchableOpacity
                        style={styles.clearBtn}
                        onPress={onBackdropPress}
                      >
                        <Text style={styles.clearTxt}>Cancel</Text>
                      </TouchableOpacity>
                      <TouchableOpacity
                        style={styles.ApplyBtn}
                        onPress={handleSubmit}
                      >
                        {isloading ? (
                          <ActivityIndicator
                            size={'small'}
                            color={colors.white}
                          />
                        ) : (
                          <Text style={styles.ApplyTxt}>Submit</Text>
                        )}
                      </TouchableOpacity>
                    </View>
                  </View>
                </>
              )}
            </Formik>
          </ScrollView>
        </Modal>
      </KeyboardAvoidingView>
    </SafeAreaView>
  )
}

const styles = StyleSheet.create({
  mainContainer: {
    backgroundColor: '#FFFFFF',
    borderTopRightRadius: 20,
    borderTopLeftRadius: 20,
  },
  madalStyle: { justifyContent: 'flex-end', margin: 0 },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignContent: 'center',
    height: 42,
    paddingHorizontal: 20,
    backgroundColor: colors.primary,
    borderTopRightRadius: 20,
    borderTopLeftRadius: 20,
  },
  headerText: {
    alignSelf: 'center',
    color: '#fff',
  },
  closeImg: {
    height: 30,
    width: 30,
    marginTop: 5,
  },
  placeholderTxt: {
    color: 'rgba(82, 83, 83, 0.5)',
    marginHorizontal: 10,
    alignSelf: 'center',
    fontSize: 16,
  },
  selectedTxt: {
    color: colors.dark,
    marginHorizontal: 10,
    alignSelf: 'center',
    fontSize: 16,
  },

  datePickerView: {
    height: 42,
    width: '100%',
    borderWidth: 1,
    borderColor: colors.lightGray,
    borderRadius: 6,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  pickerImg: {
    height: 30,
    width: 30,
    marginTop: 5,
    marginHorizontal: 15,
  },
  errorText: {
    color: colors.danger,
    // fontSize: 14,
    // margin: 5,
  },
  textInput: {
    borderColor: colors.lightGray,
    borderWidth: 1,
    borderRadius: 6,
    paddingHorizontal: 10,
    minHeight: 90,
    textAlignVertical: 'top',
    fontSize: 16,
    color: colors.dark,
  },

  lableStyle: {
    fontSize: 16,
    marginVertical: 10,
    color: colors.gray,
  },

  btnView: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    marginVertical: 20,
  },
  clearBtn: {
    borderRadius: 24,
    borderWidth: 2,
    borderColor: colors.primary,
    marginHorizontal: 20,
  },
  clearTxt: {
    color: colors.primary,
    paddingVertical: 8,
    paddingHorizontal: 15,
  },
  ApplyBtn: {
    borderRadius: 24,
    backgroundColor: colors.primary,
    paddingHorizontal: 16,
    paddingVertical: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  ApplyTxt: {
    color: '#fff',
  },
})

export default RejectionModal

```this is my component but on first click no api call just keyborad hide

**Comment by talktothelaw** [comment]
i'm still having this issue

**Comment by Adil7767** [comment]
I have fixed that by using in parent component=> in scrollView and if flatlist.

  keyboardDismissMode="interactive"
                  keyboardShouldPersistTaps={
                    Platform.OS === 'ios' ? 'handled' : 'always'
                  }

**Comment by manan-schmooze** [comment]
> Is your content wrapped in a `<ScrollView />`? If so, try `keyboardShouldPersistTaps={'handled'}` in `<ScrollView>` props.

What if it is not wrapped in a scrollview?

**Comment by gshoanganh** [comment]
> I had this issue and where trying to add Scroll View with `keyboardShouldPersistTaps="always"` with no result. Later I've found that there was a ScrollView at the page where the modal located which wrapped a whole page. So all what I did: I added `keyboardShouldPersistTaps="handled"` to this ScrollView and it helped me.
> 
> So the main idea is to walk up through the component tree and find for ScrollView and add `keyboardShouldPersistTaps="handled"` to it if exists. Otherwise just add it at place where you need it.

Thanks. it's works for me.

**Comment by geoffcfchen** [comment]
> I have fixed that by using in parent component=> in scrollView and if flatlist.
> 
> keyboardDismissMode="interactive" keyboardShouldPersistTaps={ Platform.OS === 'ios' ? 'handled' : 'always' }
> 
> ```
>               flow of parent and child components also matter.
> ```

you save my life....

**Comment by pauldamico** [comment]
I also had this issue and had to add  keyboardShouldPersistTaps={'handled'} to the component FlatList which was located in a parent component.
