### ISSUE TITLE
Backdrop opacity is not working

### ISSUE THREAD

**Issue by vineelk8** [react-native-modal/react-native-modal#460]
```
<Modal
          visible={modalVisible}
          hasBackdrop={true}
          backdropOpacity={0.5}
          backdropColor={'rgba(0, 0, 0, 0.8)'}
          onBackdropPress={() => {
            setModalVisible(false);
          }}>
<Text>Modal Opened</Text>
</Modal>
```

backDropOpacity is only getting applied. When you apply and save the file it is working. Once I close and reopen the modal the backDropOpacity is not getting applied.

**Comment by sankita15** [comment]
I am able to get the backdropColor and opacity working. you can check below:
https://codesandbox.io/s/react-native-modal-example-ljze3?file=/src/App.js

**Comment by Vasault** [comment]
it doesn't work correctly, only when you interact with the modal the backdrop color appears

**Comment by sankita15** [comment]
Please check the example link given

**Comment by vineelk8** [comment]
There is an issue with the prop I placed

Previously I place visible so the backdrop is not working. The prop should be isVisible.

**Comment by yusfarhanchepa** [comment]
yes, thanks @vineelk8 .
Fixed ! after changed visible to isVisible

            <Modal
            hasBackdrop={true}
            backdropOpacity={0.2}
            backdropColor="black"
            isVisible={this.state.ModalVisibleStatus} >

**Comment by kevindavis** [comment]
The docs (https://reactnative.dev/docs/modal#visible) indicate the property is named visible - it seems like this behavior is different when using isVisible. A bit confusing. 

A few other things I found:
- while using `visible` you can set the `backgroundColor` property .. but.. the background animates upwards with the rest of the modal
- `onBackdropPress` seems to work with both `visible` and `isVisible`
- you can use an rgba color to set transparency with backdrop color

I'm still not where I'd like to be, as I want the backdrop color (20% opacity black in my case) to set, then the modal to animate

**Comment by jbnunn** [comment]
Changing to `isVisible` worked for me too. Shouldn't this bug be addressed in the react-native-modal documentation? [The prop is currently referenced as `visible`](https://reactnative.dev/docs/modal#visible), not `isVisible`.
