### ISSUE TITLE
onBackdropPress not trigger

### ISSUE THREAD

**Issue by gandarain** [react-native-modal/react-native-modal#466]
## Environment

System:
    OS: macOS 10.15.5
    CPU: (4) x64 Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz
    Memory: 27.93 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.2 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.1
      System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom_64
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.0 => 0.61.0
  npmGlobalPackages:
    react-native-cli: 2.0.1

## Platforms

I try in Android, i dont know how in ios.

## Versions

- Android:
- iOS:
- react-native-modal: 11.5.6
- react-native: 0.61.0
- react: 16.9.0

## Description

I try to close modal when user press back drop, but the prop onBackdropPress not trigger.

# Reproducible Demo

````
<Modal
  useNativeDriver={true}
  animationIn={'fadeIn'}
  animationOut={'fadeOut'}
  backdropColor={'rgba(0, 0, 0, 0.7)'}
  backdropOpacity={0.5}
  isVisible={this.props.isOpenConsultant}
  onSwipeComplete={() => this.props.close()}
  swipeDirection={['down']}
  style={{ justifyContent: 'flex-end', margin: 0 }}
  onBackButtonPress={() => this.props.close()}
  onBackdropPress={() => console.log('Hello')}>
````

**Comment by QingyuChai** [comment]
Make sure the child component of the modal does not have { flex:1 }, as that sees to overwrite the touch trigger.

**Comment by CypherPoet** [comment]
@QingyuChai I was was having the same issue and this worked for me.

**Comment by yjb94** [comment]
I just managed to make a PR for this. In urgent cases, you can just get codes from my repository

**Comment by yjb94** [comment]
Finally... I fixed this bug in #485. Hope my PR is merged soon

**Comment by iarmankhan** [comment]
when will this get fixed @yjb94 ? I'm having the same issue, I can only close the modal by touching the statusbar in iPhone

**Comment by iarmankhan** [comment]
Is there any workaround for now? Until this get fixed by library?

**Comment by yjb94** [comment]
@iarmankhan It's been a while so i am not sure i can explain the code...but you can look on to my PR probably

**Comment by NathanBeesley** [comment]
@iarmankhan || @yjb94  Im not sure what you guys are dealing with. I have created a snack and it seems to work fine. Can you check it out and let me know so I can close this. 

Expo Snack: https://snack.expo.io/@nathanbeesley/rn-modal-backdrop

**Comment by thanh90** [comment]
> Make sure the child component of the modal does not have { flex:1 }, as that seems to overwrite the touch trigger.

That's correct

**Comment by LordParsley** [comment]
Alternatively, if you need a view with `{flex: 1}`, you can add `pointerEvents="box-none"` to it so that it is transparent to touches.

**Comment by danial-babar** [comment]
> Make sure the child component of the modal does not have { flex:1 }, as that seems to overwrite the touch trigger.

Thanks, Yes it's true. But sometime we need to set {Flex:1} to child component. So in this case make child component as a Pressable, and closeModal onPress.

**Comment by olayemii** [comment]
Also if the child has a `height: 100%` could cause this issue. I will advice adding an alternate background to the child with `backgroundColor: 'red'` or whatever color so you can visually see the bounds of the child and confirm if the press events actually gets to the backdrop.
