### ISSUE TITLE
Add props to overwrite hardcoded "4" in PanResponder.create

### ISSUE THREAD

**Issue by Aryk** [react-native-modal/react-native-modal#469]
In reference to:

https://github.com/react-native-community/react-native-modal/pull/197

Depending on the usage, maybe "5" is desirable, for others maybe"3" is, any reason we cannot make this a prop like "panResponderThreshold" so that we have control over what registers as a press and what registers a swipe gesture?

I would consider this a "bug" because as long as users press expecting an onPress event and have it fail intermittently, it could confuse them or worse frustrate them as is currently happening to my test users. I ask them to select rows in the modal, and every 10-15 rows will get missed because it will register as a "swipe" instead of a press especially if they "roll" their finger slightly when they reach for a row to select.

Increasing the value higher to 8,9,10 solved this issue while still making it possible to swipe the modal down.

**Comment by Aryk** [comment]
It's been 6 months, is there another process to have this issue looked at?

**Comment by mmazzarolo** [comment]
👋 @Aryk feel free to submit a PR
