### ISSUE TITLE
statusBarTranslucent and visible types

### ISSUE THREAD

**Issue by Ishdril** [react-native-modal/react-native-modal#486]
## Ask your Question

Hi! We're using this dependency for one of our projects setup with typescript and it's been complaining about a couple of props that we're using: statusBarTranslucent (boolean) and visible (also a boolean). They're both working fine because they act on the native modal component, but not recognized by typescript because their types are not imported in your component. 

Is there a reason for not doing so? Would you mind including them in a future release? 
Thanks a lot

**Comment by b3coded** [comment]
I've added this prop on #420 but still waiting for a new release

**Comment by Ishdril** [comment]
Thanks for your answer João. I had no idea this was on the way. I'll await for the next release then. Closing this comment
