### ISSUE TITLE
Modal affecting Swipeable Gesture on Android

### ISSUE THREAD

**Issue by jackilex** [react-native-modal/react-native-modal#494]
## Versions

- Android:
- iOS:
- react-native-modal:
- react-native:
- react:

## Description

When using "Modal" for Android; the "Swipeable" gesture handler does not work only on android

**Comment by IbrahimCanKALYA** [comment]
@jackilex did you find any solution about this issue

**Comment by jackilex** [comment]
> @jackilex did you find any solution or trick about this issue
> 

I went with another technique (hold gesture) In the meantime. I will be going over it again to see what the problem... It seems that it is the modal. I need to review my codes. It might also be because I have a <View> inside the modal. Not sure yet until I review it... But iOS didn't have that issue

**Comment by babyrusa** [comment]
@jackilex  hi were u able to figure out why

**Comment by jackilex** [comment]
No sorry. At that time I ended switching over to Flutter
