### ISSUE TITLE
Lacking Documentation for Animations

### ISSUE THREAD

**Issue by tim92109** [react-native-modal/react-native-modal#515]
Would it be too difficult to mention all the options for 'animationIn' and 'animationOut' as opposed to just mentioning 2 of them?  That would be helpful.

**Comment by tim92109** [comment]
Yes, could probably pick through all the source code to find out, but not very efficient use of time.

**Comment by mmazzarolo** [comment]
Hey @tim92109 , thanks for the feedback. This is an open-source project, feel free to contribute to the docs if you feel they're not detailed enough. 
Also, https://github.com/react-native-modal/react-native-modal/issues/414

**Comment by tim92109** [comment]
Ah ok.  I never thought about contributing to docs.  If I ever take the time to dig through and find the animation options, I'll do that.
