### ISSUE TITLE
Modal closes after mutating parent's state

### ISSUE THREAD

**Issue by AlexWang18** [react-native-modal/react-native-modal#527]
New to React Native and React in general, so pardon me if this is a stupid question.

I have my components structured so that my modal is rendered over a parent depending on a button press. I pass some of the parents state / state functions into the Modal component through props. Where I run into issues is when I try to change the parents state which causes the Modal to crash and requires me to click on the button twice to toggle it back on (since the Modal was never properly exited?). After it reopens all the data is correctly updated but I'm just sure what causes the crash. 
I ran into a similar issue when using the normal Modal component packaged with Native where after mutating the parent's state the modal would close really quickly then reopen with the correct data. 
Am I not allowed to do this? Any help / guidance is appreciated

**Comment by NathanBeesley** [comment]
What does your component structure look like? Are you conditionally rendering a modal and parent component? 

For instance: 
const i = 5 

const

**Comment by NathanBeesley** [comment]
Sounds to me with little steps to repro is that you are losing state between re renders. Are you forgetting to spread existing state, i.e setting some type of state without maintaining existing? 
setState(currentState => {...currentState, f_name: 'Nathan' }). 

I see this is a bit old. Hopefully your figured it out by now.
