### ISSUE TITLE
width content of modal 100%

### ISSUE THREAD

**Issue by agnasari** [react-native-modal/react-native-modal#528]
Hi,

How to width 100% in children of modal? i want to cover all width when styling view in modal childen, example: 
```
   <Modal isVisible={props.visible}
      backdropOpacity={0.5}
      onBackdropPress={props.onRequestClose}>
      <View style={{width: '100%'}>
        <Text>ini modal</Text>
        <Button
          mode="contained"
          dark={true}
          onPress={() => props.onRequestClose()}>
          exit
        </Button>
      </View>
    </Modal>
```

**Comment by pratius** [comment]
I have fixed using the below code
<Modal isVisible={true} style={{
                    top: 0,
                    left: 0,
                    right: 0,
                    padding: 0,
                    margin: 0,
                    marginHorizontal: 0,
                    justifyContent: 'flex-end',

                }}>

**Comment by dayaki** [comment]
Solution in stated in the documentation -> [The modal is not covering the entire screen](https://github.com/react-native-modal/react-native-modal#the-modal-is-not-covering-the-entire-screen)

using `style={{margin: 0}}` should make it work.

**Comment by mmazzarolo** [comment]
Thank you @dayaki . Closing!
