### ISSUE TITLE
override  Modal props

### ISSUE THREAD

**Issue by eran88** [react-native-modal/react-native-modal#529]
## Ask your Question

Can you add a method to override modal props?
For example, I want to use onRequestClose prop in order to close the modal when the user using the android back button.

**Comment by mmazzarolo** [comment]
Hi! 
I'm closing this issue because it's a question and not a bug report.    
If you're still looking for feedback/answers, could you please ask your question in a new [discussion](https://github.com/react-native-modal/react-native-modal/discussions)?  
Thank you!
