### ISSUE TITLE
Running examples from the app

### ISSUE THREAD

**Issue by JDMathew** [react-native-modal/react-native-modal#530]
## Ask your Question
I'm struggling to run the examples from the app.

I have cloned the repo and in the root I `cd examples/` and then I run, `yarn` and `npx pod-install` followed by `yarn start` and in a new terminal `react-native run-ios`

The app runs but with errors. Is there a guid to running the examples in the app?

**Comment by NathanBeesley** [comment]
There are currently issues if you run the app on iOS with an updated version of Xcode 12.5 and are aware of this issue. We are waiting to merge a pull request that will fix this issue. It currently needs to be tested first.
