### ISSUE TITLE
Why do I get the warning that transparent value is not supported?

### ISSUE THREAD

**Issue by simpslandyy** [react-native-modal/react-native-modal#533]
## Ask your Question

When I set the `presentationStyle` to `pageSheet`I get the warning:
`Modal with 'pageSheet' presentation style and 'transparent' value is not supported`

And when I try to set `transparent={false}` I get the warning that `transparent` is not a support prop.
Looking at the codebase, I noticed `transparent` isn't an accepted prop and it's always set to `true`
Is this a bug or am I misunderstanding the requirements for using `presentationStyle`?

![image](https://user-images.githubusercontent.com/12716559/113344096-a7d47800-92fe-11eb-81b5-837736109e7a.png)

**Comment by runata** [comment]
Same here

**Comment by NathanBeesley** [comment]
Im thinking this isn't a bug as the platform adds the transparent layer automatically. 

https://developer.apple.com/documentation/uikit/uimodalpresentationstyle/pagesheethttps://developer.apple.com/documentation/uikit/uimodalpresentationstyle/pagesheet

**Comment by MahmoudBahar** [comment]
that warning still shows any solutions?
