### ISSUE TITLE
onModalHide is not getting called at the very *very*end

### ISSUE THREAD

**Issue by Aryk** [react-native-modal/react-native-modal#534]
Even when using onModalHide I'm running into issues when I want to display for example an Alert.alert from onModalHide...

It will show up for a split second and disappear.

If I use setTimeout(func, 10), it will work. Has anyone else encountered this?

Also, I believe there will also be problems if you "show" another modal on onModalHide from a previous modal.

Ive read this [one](https://github.com/react-native-modal/react-native-modal/issues/484) which was solved by onModalHide. 

Snack: https://snack.expo.io/@tennisbum/anxious-tortilla

If you uncomment the line that I commented, you'll see that the 10ms timeout works (in this case). Maybe doesn't always work if the phone is slower for example... :/

However, I'm talking about something else. I don't believe onModalHide is being call after the modal is hidden *and* screen is repainted. It's not "completely" closed which makes it difficult to chain things after and causes glitches.

**Comment by hmarques98** [comment]
Hi there, I also passed for same problem that you. I resolved this problem using the hook useRef and give to him the value boolean. 

Kind
`  const modalRef = useRef(false);`
`onModalHide={() => {
          modal.current && setIsVisibleSuccessTrash(true);
 }}`

`onConfirm={() => {
          modalTrash.current = true;
          setIsVisibleModalTrash(false);}}`

I hope that I helped you

**Comment by Aryk** [comment]
I guess Im just confused on the implementation... `onConfirm` is on a button press, is that right?

**Comment by hmarques98** [comment]
Sorry for confusion. 

setIsVisibleModalTrash to false would be first modal that is showing. Then when press to hide him, on onModalHide props function i call modalRef.current && setIsVisibleSuccessTrash(true) that is second modal to show after the other modal. 

onConfirm is just a custom props from my custom component

**Comment by NathanBeesley** [comment]
Are you using two separate states for each modal?

**Comment by hmarques98** [comment]
> Are you using two separate states for each modal?
One state to first modal and another to second modal. And a boolean with useRef.
When first modal on Hide him I do the conditional with current useRef

**Comment by NathanBeesley** [comment]
useRef hook does not cause re renders. What are you using the ref for? You should be modifying the state value for the second modal instead.

**Comment by NathanBeesley** [comment]
Does this expo snack help you? I am going to close this as I believe this is not a react-native issue. Hope this snack helps.

_For this specific issue_
https://snack.expo.io/@nathanbeesley/react-native-modal

_Other snacks you can fork and play with
https://expo.io/@nathanbeesley?tab=snacks_
