### ISSUE TITLE
Auto focusing is not working on screen after react-native-modal

### ISSUE THREAD

**Issue by rener172846** [react-native-modal/react-native-modal#536]
## Environment

```
  System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
    Memory: 55.09 MB / 5.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 15.2.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.0.10 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    Android SDK:
      API Levels: 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2
      System Images: android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.2/12B45b - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_275 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
  `  `*react-native*: Not Found
```

## Platforms

issue found on **iOS**
I haven't tested on **Android** yet

## Versions

- iOS: 14.2
- react-native-modal: 11.6.1
- react-native: 0.63.4
- react: 16.13.1

## Description

  In my app, there is an `AddingItemModal` which is based on `react-native-modal`, once user choose any type of item on this modal it will be directed to the `AddItemScreen` which has some input fields for detailed information depends on that type of item.
  The problem is that after `AddItemScreen` is pushed, auto focusing on the first input field is not working. The auto focusing is working well if I only change the modal to default `Modal` component from `react-native`.

**Comment by jiyuan12354** [comment]
I have also encounterred this issue, but I only reproduced it in android..IOS is ok for me

**Comment by TheRogue76** [comment]
Hi @rener172846. A couple of questions:
1. Can you give a reproducible piece of code?
2. Do you navigate to the screen first and then set the modal's visibility to false or do you set the visibility to false and then use ```useEffect``` to navigate to ```AddItemScreen```?
3. what navigation system are you using? React Navigation or React Native Navigation?

**Comment by ashish-hiverhq** [comment]
did a workaround by using setTimeout to navigate the user, Working on both platforms

**Comment by NathanBeesley** [comment]
You could use onModalHide property to ensure the modal is hidden before you navigate. Closing the for now as it has been inactive for some time.
