### ISSUE TITLE
TouchableHighlight blocks scrolling on Scrollable Modal

### ISSUE THREAD

**Issue by Sunhat** [react-native-modal/react-native-modal#538]
Firstly, your form fields are too long and annoying to fill out and aren't always necessary

## Platforms

Tested on Android only

## Versions

- Android: 10
- react-native-modal: latest
- react-native: latest 
- react: idk

## Description

When using the ScrollableModal, if you place buttons on TouchableHighlights or other buttons, the scroll/drag doesn't work if you try to drag from the button.

This doesn't happen on instagrams scrollable modal.

**Comment by mmazzarolo** [comment]
Hola!

> Firstly, your form fields are too long and annoying to fill out and aren't always necessary

If they aren't necessary, you probably already figured out how the issue should be fixed. In this case, feel free to submit a pull-request! Thanks!

**Comment by Sunhat** [comment]
Bit toxic, but okay
