### ISSUE TITLE
Backdrop not covering the whole screen when navigation bar is hidden

### ISSUE THREAD

**Issue by allandiego** [react-native-modal/react-native-modal#544]
Is there anyway to fix the backdrop not covering full screen in some android devices? Maybe expose the backdropComputedStyle width height
https://github.com/react-native-modal/react-native-modal/blob/master/src/modal.tsx#L729

Some android devices return the  getDeviceWidth() getDeviceHeight() with or without navigation bar size that cause some strange behavior like this not covering the whole screen when navigation bar is hidden:
![backdrop-1](https://user-images.githubusercontent.com/6215050/115146751-3ef33c80-a02e-11eb-8863-4c954b4d23a5.jpeg)
![backdrop-2](https://user-images.githubusercontent.com/6215050/115146758-47e40e00-a02e-11eb-892a-3b7bf43fb196.jpeg)

**Comment by vapstor** [comment]
`global.maxDeviceHeight = Math.max(Dimensions.get('window').height, Dimensions.get('screen').height);`

then: 

`<Modal
                isVisible={isModalVisible}
                deviceHeight={global.maxDeviceHeight}
                statusBarTranslucent
                animationOut={"slideOutUp"}
                animationInTiming={500}
                animationOutTiming={500}
                backdropTransitionInTiming={500}
                backdropTransitionOutTiming={1000}
                onBackdropPress={() => setModalVisible(false)}
                onSwipeComplete={() => setModalVisible(false)}
                swipeDirection="up"
            >`

**Comment by allandiego** [comment]
It worked, thank you completely forgot about Dimensions can return screen height too not only window

**Comment by zoolle** [comment]
Its working but if you use `avoidKeyboard={true}` it will not move the modal
