### ISSUE TITLE
The method does not work correctly, the background is still not clickable.

### ISSUE THREAD

**Issue by NeznaykaGM** [react-native-modal/react-native-modal#545]
## Versions

- Android:
- iOS:
- react-native-modal:
- react-native:
- react:

**Comment by mayank-budhiraja** [comment]
Hello! If you can provide more description on the issue then I can take this one. Thanks

**Comment by NathanBeesley** [comment]
Closing as you haven't provided any repro steps let alone a description of the issue you are facing.
