### ISSUE TITLE
Always keep modal open, toggle between two heights

### ISSUE THREAD

**Issue by Sunhat** [react-native-modal/react-native-modal#547]
Hi, 

I'm using this modal in several places. The design I need to implement includes a modal stays open constantly, and moves between about 200 from the bottom, and full screen.

I'd like to know if this is possible. I can attach screenshots of designs if necessary - Thanks!

**Comment by NathanBeesley** [comment]
Are you thinking of the widget similar to how iOS maps works? Where you have a view that is barely showing

**Comment by NathanBeesley** [comment]
Here is a link to a library that does support.
https://github.com/osdnk/react-native-reanimated-bottom-sheet
