### ISSUE TITLE
Border radius not working

### ISSUE THREAD

**Issue by rajeshivn** [react-native-modal/react-native-modal#557]

**Comment by NathanBeesley** [comment]
Could you provide some more information? Version, platform etc? 

Im not at my desk at the moment but you may need to wrap the modal inside of an empty view and set the border radius there. Let me know if that works for you.

**Comment by codeidiotpro** [comment]
I've added a ```borderRadius``` to the modal and to its child ```<ScrollView>```.
as you scroll, the border becomes squared and seems like only the top and end of the ```<ScrollView>``` shows the border radius but not as you scroll.
Also how can I change the ```backgroundColor``` of the modal? The empty dark transparent space behind the modal is what I mean 

```js
<Modal
  style={styles.modalStyle}
  isVisible={true}
  scrollHorizontal={true}
  propagateSwipe={true}
>
  <ScrollView
    contentContainerStyle={styles.scrollViewStyle}
    showsVerticalScrollIndicator={false}
  >
    <View>
      <Text>text</Text>
      <Text>text</Text>
      <Text>text</Text>
      <Text>text</Text>
      <Text>text</Text>
      <Text>text</Text>
      <Text>text</Text>
      <Text>text</Text>
      <Text>text</Text>
      <Text>text</Text>
      <Text>text</Text>
      <Text>text</Text>
      <Text>text</Text>
      <Text>text</Text>
      <Text>text</Text>
      <Text>text</Text>
      <Text>text</Text>
      <Text>text</Text>
      <Text>text</Text>
      <Text>text</Text>
      <Text>text</Text>
      <Text>text</Text>
      <Text>text</Text>
      <Text>text</Text>
      <Text>text</Text>
      <Text>text</Text>
      <Text>text</Text>
      <Text>text</Text>
      <Text>text</Text>
      <Text>text</Text>
      <Text>text</Text>
      <Text>text</Text>
    </View>
  </ScrollView>
</Modal>

const styles = StyleSheet.create({
  modalStyle: {
    marginTop: 18,
    marginLeft: "auto",
    marginRight: "auto",
    borderRadius: 20,
    height: "90%",
    width: "90%",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  scrollViewStyle: {
    borderRadius: 20,
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "white",
  },
});

```

**Comment by IvKr95** [comment]
> Also how can I change the `backgroundColor` of the modal? The empty dark transparent space behind the modal is what I mean

Use backdropColor and backdropOpacity

**Comment by NathanBeesley** [comment]
I think what you want here is to add borderRadius to both contentContainerStyle and style. What you are seeing is clipping from the parent container. 

Here is a snack -> https://snack.expo.io/@nathanbeesley/react-native-modal-sv-border-radius
