### ISSUE TITLE
Alert to be displayed after modal closes. Alert getting dismissed automatically in a fraction of second in iOS.

### ISSUE THREAD

**Issue by hk22sync** [react-native-modal/react-native-modal#563]
## Platforms

 iOS 

## Versions

- iOS: iPadOS 13.5.1
- react-native-modal: 11.5.3
- react-native: 0.61.2
- react:16.9.0

## Description

 I have a custom Loader component built using ActivityIndicator from React and Modal from react-native-modal.
Steps:
1. On main page(App.js) user clicks on GetData button.
2. Loader appears and API call is made.
3. After API call is done modal dismisses.
4. An alert is supposed to be displayed after that but it appears for a fraction of seconds and dismisses automatically.

This issue occurs only in case of iOS.

## Reproducible Demo

https://snack.expo.io/@hk22sync/bd2344

**Comment by hk22sync** [comment]
> So what you are seeing is an issue when rendering. You are showing the alert too quickly, when rendering the Alert it is attached to the modal which is in the process of hiding. I have changed the Expo Snack to reflect how it could be done. There are different ways to achieve this. the Expo Snack https://snack.expo.io/@nathanbeesley/alert-issue-with-ios has been updated

Thank you for the solution. It works.
Is there any other way we can achieve this without the use of timeout?

**Comment by NathanBeesley** [comment]
@hk22sync. I have updated the following expo. https://snack.expo.io/@nathanbeesley/alert-issue-with-ios. It is in no way perfect but there to give you the idea.

**Comment by hk22sync** [comment]
> @hk22sync. I have updated the following expo. https://snack.expo.io/@nathanbeesley/alert-issue-with-ios. It is in no way perfect but there to give you the idea.

I want to understand if we can fix it in the library itself?

**Comment by NathanBeesley** [comment]
It's more of the way react-natives lifecycle events and renders work.
