### ISSUE TITLE
Update samples to showcases React functional style instead of, or in addition to classes.

### ISSUE THREAD

**Issue by vgribok** [react-native-modal/react-native-modal#564]
I am trying to understand how <MyChildComponent/> component that can trigger state change in the <ParentComponent/> in the real-world example done in the functional style with hooks. Current examples in the "example" directory appear to use class/oop style exclusively instead.

**Comment by NathanBeesley** [comment]
Will something like this give you a better idea? I have created a snack that you can checkout. 

https://snack.expo.io/@nathanbeesley/alert-issue-with-ios
