### ISSUE TITLE
Modal don't show

### ISSUE THREAD

**Issue by minh-dai** [react-native-modal/react-native-modal#574]
I have a question. when my app is foreground, I would show a modal, then the background modal will close, but I using appState, the modal doesn't show. How i can show a modal when the app is foreground ?? like paypal

**Comment by hoanglam10499** [comment]
it's not modal. You can see instructions and follow:
https://jonaskuiler.medium.com/creating-a-security-screen-on-ios-and-android-in-react-native-97703092e2de
or use
`rnbootsplash`

hope this helps

**Comment by minh-dai** [comment]
@hoanglam10499 thanks :)))
