### ISSUE TITLE
type error in version 12.0.3

### ISSUE THREAD

**Issue by souzaluiz** [react-native-modal/react-native-modal#583]
updated to version 12.0.3, and now the deviceHeight prop is with type null | undefined

![image](https://user-images.githubusercontent.com/29143315/127392274-08af2428-f29f-4518-9832-a411e75047e6.png)

**Comment by exneval** [comment]
type for deviceHeight and deviceWidth should be updated

please look into this @mmazzarolo

**Comment by exneval** [comment]
Fixed in v12.1.0
Thank you
