### ISSUE TITLE
EventEmitter.removeListener('didUpdateDimensions', ...): Method has been deprecated. Please instead use `remove()` on the subscription returned by `EventEmitter.addListener`.

### ISSUE THREAD

**Issue by woltob** [react-native-modal/react-native-modal#588]
Before putting more information here: Has anyone seen this and know how to fix it?

```
index.js:1 EventEmitter.removeListener('didUpdateDimensions', ...): Method has been deprecated. Please instead use `remove()` on the subscription returned by `EventEmitter.addListener`.
```

"react-native-modal": "^12.0.3",
"react-native": "https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz",
"react": "16.13.1",

Let me know if you need more information.
Thanks!

**Comment by paulignupplabs** [comment]
getting the same error on web platform

**Comment by talaikis** [comment]
Same with `12.1.0` and RN `0.65`

**Comment by mmazzarolo** [comment]
https://github.com/react-native-modal/react-native-modal/pull/594

**Comment by matthieunelmes** [comment]
Still having this problem with 13.0.0 and 0.65.1

**Comment by matthieunelmes** [comment]
Apologies, a different component was triggering the deprecation warning, all's fine here.

**Comment by jvictorjs** [comment]
Having this problem:
    "expo": "^45.0.5",
    "react": "17.0.2",
    "react-native": "0.68.2",
    "react-native-modal": "^13.0.1",

EventEmitter.removeListener('didUpdateDimensions', ...): 
Method has been deprecated. Please instead use `remove()` on the subscription returned by `EventEmitter.addListener`.
at node_modules\expo\build\environment\react-native-logs.fx.js:18:4 in warn
at node_modules\react-native\Libraries\vendor\emitter\_EventEmitter.js:164:4 in EventEmitter#removeListener       
at node_modules\react-native-modal\dist\modal.js:414:8 in ReactNativeModal#componentWillUnmount

**Comment by vaish8529** [comment]
Any update?

**Comment by mja-maia** [comment]
I'm still having this issue on `react-native-modal` 13.0.1

**Comment by ronaldaraujo** [comment]
Here it is solved. Thanks!
