### ISSUE TITLE
KeyboardAvoidView getting push up when TextInput in modal have 'avoidKeyboard' properties

### ISSUE THREAD

**Issue by WenLonG12345** [react-native-modal/react-native-modal#611]
Hi, I am new to React Native and I am recently working on putting a modal dialog inside my app. 
Here is the screenshot.

![image](https://user-images.githubusercontent.com/39330565/134606957-b3914da2-852f-443c-a8c4-fd4f2e297f84.png)

I have my main screen which are wrapped with `KeyboardAvoidView` and also enable `avoidKeyboard` props to the modal. 
However, when TextInput in modal is focused, the keyboard push the main screen as well. 
How can I make only the modal dialog is avoiding keyboard? 
May I know anything I had done wrongly?

**Comment by mmazzarolo** [comment]
👋 please use the [discussions](https://github.com/react-native-modal/react-native-modal/discussions) for Q&A
