### ISSUE TITLE
Modal crashes on `react-native@0.66`

### ISSUE THREAD

**Issue by harleenarora** [react-native-modal/react-native-modal#615]
App crash on IOS devices on click modal. After update the react-native 0.66.0 version.

## Platforms

Crash on IOS platform

## Versions

- react-native-modal:13.0.0
- react-native:0.66.0
- react:17.0.2

## Description

`Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x11b928 __exceptionPreprocess
1  libobjc.A.dylib                0x26480 objc_exception_throw
2  UIKitCore                      0x47cd4c -[UIViewController popoverPresentationController:]
3  UIKitCore                      0x47d7c0 __63-[UIViewController _presentViewController:animated:completion:]_block_invoke_2
4  UIKitCore                      0x102329c +[UIView(Animation) performWithoutAnimation:]
5  UIKitCore                      0x47d720 __63-[UIViewController _presentViewController:animated:completion:]_block_invoke
6  UIKitCore                      0x496754 -[_UIViewControllerTransitionCoordinator _applyBlocks:releaseBlocks:]
7  UIKitCore                      0x492ff0 -[_UIViewControllerTransitionContext _runAlongsideCompletions]
8  UIKitCore                      0x492d1c -[_UIViewControllerTransitionContext completeTransition:]
9  UIKitCore                      0xfcfee4 -[_UIAfterCACommitBlock run]
10 UIKitCore                      0xb3f9c4 _runAfterCACommitDeferredBlocks
11 UIKitCore                      0xb2ee90 _cleanUpAfterCAFlushAndRunDeferredBlocks
12 UIKitCore                      0xb601e0 _afterCACommitHandler
13 CoreFoundation                 0x99c40 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__
14 CoreFoundation                 0x94270 __CFRunLoopDoObservers
15 CoreFoundation                 0x9480c __CFRunLoopRun
16 CoreFoundation                 0x93ed0 CFRunLoopRunSpecific
17 GraphicsServices               0x3570 GSEventRunModal
18 UIKitCore                      0xb302d0 -[UIApplication _run]
19 UIKitCore                      0xb3584c UIApplicationMain
21 libdyld.dylib                  0x1140 start`

**Comment by mmazzarolo** [comment]
Hey! Thanks for reporting. 
Yeah, it's an open issue of React Native's built-in modal https://github.com/facebook/react-native/issues/32329

**Comment by mmazzarolo** [comment]
👍 closing.

**Comment by danielmark0116** [comment]
Hi, just writing a small FIY for anyone having a similar issue with modals freezing the app on iOS.

In my case it was happening only on `release` type of builds.

What was causing the issue was the animated bar component (simple line that was being animated over time). Basically the bar was representing a countdown and the modal could be opened during the animation.

The line had `width` property animated with reanimated (v2). After changing the animation to target `translateX` in place of `width`, the problem disappeared :)
