### ISSUE TITLE
The animation is not sliding from the bottom

### ISSUE THREAD

**Issue by lunalu-27** [react-native-modal/react-native-modal#618]
## Environment

System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 4.86 GB / 15.71 GB
  Binaries:
    Node: 16.11.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.0.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 29, 30, 31
      Build Tools: 29.0.2, 30.0.2, 31.0.0
      System Images: android-29 | Google APIs Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7784292
    Visual Studio: 16.11.31727.386 (Visual Studio Community 2019)
  Languages:
    Java: 1.8.0_302 - C:\Program Files\OpenJDK\openjdk-8u302-b08\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Versions

- Android:  Android 11 (API level 30) 
- iOS:
- react-native-modal: ^13.0.0
- react-native: 0.66.1
- react: 17.0.2

## Description

Hi all,
I'm customing a bottom sheet,
so the animation is not sliding from the bottom when I add statusBarTranslucent, i need a help
Tks all 

## Demo
https://user-images.githubusercontent.com/59393413/138586228-31b12690-515c-4a40-a43d-9b2403b9f879.mp4
https://user-images.githubusercontent.com/59393413/138586229-c67fabda-4e44-4074-be8d-9df769308f1f.mp4

**Comment by aliraza96** [comment]
I am also facing this issue. Sometimes, the modal dissapears towards top

**Comment by babyrusa** [comment]
Can you share some of your code where you set animation? the Animation not working for me. Thank you
