### ISSUE TITLE
Backdrop doesn't cover the StatusBar (Android)

### ISSUE THREAD

**Issue by alexis-regnaud** [react-native-modal/react-native-modal#638]
## Environment

```
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Memory: 1.75 GB / 15.82 GB
  Binaries:
    Node: 14.15.4 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.10 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.1
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
    Windows SDK:
      AllowAllTrustedApps: Disabled
      Versions: 10.0.17763.0
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6953283
    Visual Studio: Not Found
  Languages:
    Java: 1.8.0_275 - C:\Program Files\OpenJDK\openjdk-8u275-b01\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.3 => 0.64.3
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Platforms

Android

## Versions

- Android:
- iOS:
- react-native-modal: 13.0.0
- react-native: 0.64.3
- react: 17.0.1
- expo: 44.0.5

## Description

On Android the Backdrop doesn't cover the StatusBar. 

![271918180_354675636484632_5253943028790051611_n](https://user-images.githubusercontent.com/15250423/151835385-158297e0-a1e9-4285-a662-b1325853e94d.jpg)

I already checked within my code and the Modal is implemented outside ReactNavigation or SafeAreaView (Which could add some safespace).
Since I am on expo, I cannot implement [The backdrop is not completely filled/covered on some Android devices (Galaxy, for one)](https://github.com/react-native-modal/react-native-modal#the-backdrop-is-not-completely-filledcovered-on-some-android-devices-galaxy-for-one) (Du to [react-native-extra-dimensions-android](https://github.com/Sunhat/react-native-extra-dimensions-android)). I tried a workaround by using `useSafeAreaFrame`, `useSafeAreaInsets `from [react-native-safe-area-context](https://docs.expo.dev/versions/latest/sdk/safe-area-context/) but that doesn't seem to have any impact.

I checked on IOS and everything works as expected :

![272048832_543555289945854_9151352767394767071_n](https://user-images.githubusercontent.com/15250423/151837600-41d464cf-3c6e-42a2-82d8-137c1d8dbb46.png)

## Reproducible Demo

https://snack.expo.dev/@alexis.regnaud/demo-react-native-modal

You should see on the snack that the statusbar is covered on IOS but not on Android

**Comment by rafmrs** [comment]
I have the same problem. Tried with a Samsung Galaxy S10e. Any ideas for a fix?

**Comment by souzaluiz** [comment]
@rafmrs @alexis-regnaud I solve like this.
```js
const { height } = Dimensions.get('screen');

function Component () {
  return (
    <Modal 
      isVisible={true} 
      deviceHeight={height}
      statusBarTranslucent
    >
      ....
    </Modal>
  );
}
```

**Comment by alexis-regnaud** [comment]
It has worked on my side! But I have got a Typescript issue : 
`TS2322: Type 'string' is not assignable to type 'number | null | undefined'.` 
 `deviceHeight` should accept a string to handle that case.

**Comment by alexis-regnaud** [comment]
That code worked also : 
```
const { height } = Dimensions.get('screen');

function Component () {
  return (
    <Modal 
      isVisible={true} 
      deviceHeight={height}
      statusBarTranslucent
    >
      ....
    </Modal>
  );
}
```
I think in my case `statusBarTranslucent` was the props which was missed.

**Comment by daheeahn** [comment]
> @rafmrs @alexis-regnaud I solve like this.
> 
> ```js
> function Component () {
>   return (
>     <Modal 
>       isVisible={true} 
>       deviceHeight="100%"
>       statusBarTranslucent
>     >
>       ....
>     </Modal>
>   );
> }
> ```

thx!

**Comment by maik-emanoel** [comment]
> @rafmrs [@alexis-regnaud](https://github.com/alexis-regnaud) I solve like this.
> 
> function Component () {
>   return (
>     <Modal 
>       isVisible={true} 
>       deviceHeight="100%"
>       statusBarTranslucent
>     >
>       ....
>     </Modal>
>   );
> }

This solved the problem to me. Thanks, man.
