### ISSUE TITLE
Modal not open when navigate back to screen

### ISSUE THREAD

**Issue by DongjingZhong** [react-native-modal/react-native-modal#660]
## Versions

- Android:
- iOS:
- react-native-modal:
- react-native:
- react:

**Comment by CMDezz** [comment]
still get this error

**Comment by viethung0823** [comment]
I guess this issue occurs because the state of the modal was reset when you navigate back. It likely not a bug. But I still find a way to resist the modal state as open when navigate to other screen without set it off.
