### ISSUE TITLE
react-native-modal does not work when react-native-inappbrowser is open (iOS only)_

### ISSUE THREAD

**Issue by khj3132** [react-native-modal/react-native-modal#735]
## Environment

System:
    OS: macOS 13.0
    CPU: (8) arm64 Apple M1 Pro
    Memory: 74.56 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.0 - /opt/homebrew/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.19.3 - /opt/homebrew/bin/npm
    Watchman: 2022.10.24.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.5 => 0.67.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Platforms

iOS

## Versions

- Android: -
- iOS: 16.2
- react-native-modal: 13.0.0
- react-native: 0.67.5
- react: 17.0.2

## Description

The react-native-modal does not work when react-native-inappbrowser is open on iOS env.
I set a timer with setTimeout and react-native-modal open when the timer is over.
When react-native-inappbrowser is open and the timer is over.
Then I close react-native-inappbrowser, the modal is not open.
It works fine on Android env.
Is it correct action for the modal to not open in this situation?

**Comment by sbaiahmed1** [comment]
The default behaviour in iOS is that you cant display two modals on top of each other, so maybe in the inappBroswer onClosed callback you need to reopen your modal ...

**Comment by khj3132** [comment]
Thank you for your comment.
You mean that the react-native-inappbrowser is regarded as a modal on iOS env?

**Comment by sbaiahmed1** [comment]
Yes, that’s it it’s treated as a modal

**Comment by khj3132** [comment]
I got it. I'll try what you said. Thank you.
